plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - '.idea/workspace.xml'
  - 'node_modules/*'

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

show_downloads: false
markdown: kramdown
