plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - '.idea/workspace.xml'
  - '*.iml'
  - 'node_modules/*'
  - '*.ts'
  - '*.tsx'
  - '*.puml'
  - '*.tsv'
  - 'assets/css/skyline.scss'
  - 'assets/puml/*'
  - 'Gemfile*'
  - 'package*.json'
  - 'tsconfig.json'
  - 'src/*'
  - 'assets/scss/*'
include:
  - LICENSE.md
  - CONTRIBUTING.md

theme: jekyll-theme-cayman

show_downloads: false
markdown: kramdown
