plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
relative_links:
  enabled: true
  collections: true
exclude:
  - '.idea/workspace.xml'
  - '*.iml'
  - 'node_modules/*'
  - '*.ts'
  - '*.tsx'
  - '*.puml'
  - '*.tsv'
  - 'assets/css/skyline.scss'
  - 'assets/puml/*'
  - 'Gemfile*'
  - 'package*.json'
  - 'tsconfig.json'
  - 'src/*'
  - 'assets/scss/*'
  - '.bundle/*'
  - 'vendor/*'
include:
  - LICENSE.md
  - CONTRIBUTING.md

#theme: jekyll-theme-cayman

show_downloads: false
markdown: kramdown
permalink: none

kramdown:
  auto_ids: true
  input: GFM

layouts_dir: _layouts
title: Skyline
description: Homebrew tabletop role-playing game modules unofficially set in the world of Horizon.
