plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - '.idea/workspace.xml'
  - 'node_modules/*'
  - '*.ts'
  - '*.tsx'
  - '*.puml'
  - '*.tsv'
  - 'assets/css/skyline-original.scss'
  - 'assets/puml/*'
include:
  - LICENSE.md
  - CONTRIBUTING.md

theme: jekyll-theme-cayman

show_downloads: false
markdown: kramdown
