plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - '.idea/workspace.xml'
  - 'node_modules/*'
  - '*.ts'
  - '*.tsx'
  - '*.puml'
  - '*.tsv'
  - 'assets/css/skyline-original.scss'

theme: jekyll-theme-cayman

#defaults:
#  - scope:
#      path: "assets/img"
#    values:
#      image: true

show_downloads: false
markdown: kramdown
