@startuml

' title IASO Story Graph

skinparam {
	DefaultFontName Roboto Condensed
	DefaultFontSize 16
	shadowing false
	HyperlinkUnderline false
	HyperlinkColor #000000

	
	ArrowColor #cccccc
	BackgroundColor #ffffff
	
	ActivityBackgroundColor #C8E2F9
	ActivityBorderColor #C8E2F9

  ActivityBackgroundColor<<NotStarted>> #ffff99
  ActivityBorderColor<<NotStarted>> #ffff99
  ActivityBackgroundColor<<TODO>> #eeffcc
  ActivityBorderColor<<TODO>> #eeffcc
  ActivityBackgroundColor<<OptionalEncounter>> #F9E2C8
  ActivityBorderColor<<OptionalEncounter>> #F9E2C8
  ActivityBackgroundColor<<Encounter>> #EEAD63
  ActivityBorderColor<<Encounter>> #EEAD63
  ActivityBackgroundColor<<Travel>> #BBF395
  ActivityBorderColor<<Travel>> #BBF395
	LegendBackgroundColor transparent
	LegendBorderColor transparent
	LegendBorderThickness 0
}

(*) --> "[[100-mothers-crown.html 100: Mother's Crown]]" as e100 
e100 --> "[[101-road-to-mothers-watch.html 101: The Road to Mother's Watch]]" as e101 <<Travel>>
e101 -> "[[146-scrappers-deaf.html 146]]" as e146 
e101 --> "[[147-striders-blind.html 147]]" as e147 
e101 --> "[[162-scrappers-surprise.html 162]]" as e162 
"[[102-olaras-cave.html 102: Olara & Brom]]" as e102  -> "[[141-iaso-brom.html 141]]" as e141 
e102 --> "[[124-back-to-mothers-watch.html 124]]" as e124 <<Travel>>
"[[103-cardiac-event.html 103: Forest Near Mother's Watch]]" as e103  -> "[[104-clear.html 104]]" as e104 
e104 -> "[[105-striders.html 105]]" as e105 <<Encounter>>
e105 -> "[[106-all-mother-mountain.html 106]]" as e106 
e106 -> "[[198-corruptor-module.html 198]]" as e198 
"[[107-lab.html 107]]" as e107  -> "[[108-exit.html 108]]" as e108 <<OptionalEncounter>>
e108 --> "[[156-mothers-watch.html 156: Mother's Watch]]" as e156 
"[[109-dinner.html 109]]" as e109  -> "[[115-lodging.html 115]]" as e115 
"[[110-carja-refugee-family.html 110]]" as e110  -> e109
"[[111-tradespeople.html 111]]" as e111  -> e109
"[[112-leave-tonight.html 112]]" as e112 <<OptionalEncounter>> --> "[[113-olara-and-brom-night.html 113: Olara and Brom]]" as e113 
e113 -> "[[123-iaso-brom-olara.html 123]]" as e123 
e113 --> e124
"[[114-iala-uln-jineko.html 114]]" as e114  -> e109
e115 -> "[[116-logging.html 116]]" as e116 
e116 -> "[[119-timber-and-striders.html 119]]" as e119 
"[[117-medical-focus.html 117]]" as e117  -> "[[118-focus.html 118]]" as e118 
e118 -> "[[168-power-wall.html 168]]" as e168 
e119 -> "[[122-lumber-carts.html 122]]" as e122 <<TODO>>
"[[120-scrappers-incoming.html 120]]" as e120  --> "[[173-ruins-entrance.html 173: Mother's Watch Ruins]]" as e173 
"[[121-scrappers-treeline.html 121]]" as e121  --> e173
e123 -> e124
e124 --> e103
"[[129-teb.html 129: Teb]]" as e129  -> e112
e129 --> "[[136-leave-tomorrow.html 136]]" as e136 
"[[134-synchronize.html 134]]" as e134  -> e107
e136 -> "[[137-leave-morning.html 137]]" as e137 
e136 --> "[[191-not-interested.html 191]]" as e191 <<Travel>>
e137 --> e102
e141 -> e124
e146 -> e121
e146 --> e120
e147 -> e121
e147 --> e120
"[[150-the-blinking-light.html 150]]" as e150  -> e117
e150 --> e118
e156 --> e129
e162 --> e173
e168 -> e134
e168 --> "[[186-no-synchronize.html 186]]" as e186 
e173 --> e150
e186 -> e107
e191 --> e103
e198 -> "[[199-what-next.html 199]]" as e199 
e199 --> (*)

legend
|= Type |= Description |
|<#C8E2F9> (Other) | Story |
|<#eeffcc> TODO | Story, not finished |
|<#BBF395> Travel | Party travel |
|<#EEAD63> Encounter | Combat encounter, required |
|<#F9E2C8> Optional Encounter | Combat encounter, optional |
endlegend


@enduml
